# Generated by Django 6.0.2 on 2026-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('All', 'All'), ('AI & Machine Learning', 'AI & Machine Learning'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Cybersecurity', 'Cybersecurity'), ('Programming', 'Programming'), ('Blockchain & Web3', 'Blockchain & Web3'), ('IoT & Smart Tech', 'IoT & Smart Tech')], default='All', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('excerpt', models.TextField(default='')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
    ]
